version: 0.0
os: linux
files:
  - source: index.html
    destination: /home/ec2-user/rapyder-app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/validate.sh
      timeout: 300
      runas: ec2-user
