version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies for build..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build phase completed"

artifacts:
  files:
    - appspec.yaml
    - scripts/*
    - requirements.txt
    - app.py
    - flask-app/**/*
