version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Packaging application..."
      - mkdir -p output
      - cp -r * output/
      - cd output
      - zip -r ../app.zip .
      - cd ..

artifacts:
  files:
    - app.zip
  discard-paths: yes
